FROM golang AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .


# Final stage.
FROM golang

COPY --from=builder /app/auth /app/

EXPOSE 6001

ENTRYPOINT ["/app/auth"]

