version: "3"

services:
  manager:
    container_name: manager
    build: ../manager/.
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - .env.docker:/app/.env
    depends_on:
      - mongodb
      - auth
    links:
      - mongodb
      - auth
    networks:
      - backend
      - frontend

  auth:
    container_name: auth
    build: ../auth/.
    restart: always
    ports:
      - "8081:8081"
    expose:
      - "8081"
    volumes:
      - .env.docker:/app/.env
    networks:
      - frontend

  mongodb:
    container_name: mongodb
    build: ../mongodb/.
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - .env.docker:/app/.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

